### ISSUE TITLE
IOS: Why can't we select photos from photo gallery using this plugin?

### ISSUE THREAD

**Issue by muffadal53** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#138]
In IOS, using FilePicker plugin why can't we select any photo/picture from photo gallery?

## Specifications

  - NuGet package version: 2.1.18
  - Platform(s): IOS 12.3.1

**Comment by vividos** [comment]
I guess the reason is that it's difficult to map file picking to iOS features and dialogs. Apple has decided that the photo gallery is not something you can pick from using `UIDocumentPickerViewController`. You can take a look at James Montemagno's MediaPlugin (https://github.com/jamesmontemagno/MediaPlugin) meanwhile. I guess it's at some stage incorporated into Xamarin.Essentials eventually.
