### ISSUE TITLE
NRE when selecting a file on some Android versions

### ISSUE THREAD

**Issue by VitalyKnyazev** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#143]
## Expected Behavior
No crash, NuGet libs built using Release configuration

## Actual Behavior
NRE crash as NiGet libs build using Debug configuration

## Steps to Reproduce the Problem

  1. WindsongAOB device (apparently a Bot Device owned by Google playstore Review Team)
  2. NRE within FilePickerActivity.OnActivityResult when picking a file and probably cancelling

## Specifications

  - NuGet package version: 2.1.18
  - Platform(s): Android 6.0.1

**Comment by vividos** [comment]
I'm surprised by this, but you're right, the 2.1.-Versions contain the debug version of the assemblies (visible in ILspy).

@jfversluis Could you please check the Azure build steps if we're building Debug instead of Release?

I normally wouldn't expect that a call to `System.Diagnostics.Debug.Write()` would produce a NRE in a Release setting, but maybe the WindsongAOB device is very picky. File picking works for me on Android, tested on various devices.

**Comment by jfversluis** [comment]
Hm, oddly enough I didn’t specify a build configuration. So it might as well be that it builds the debug one by default. However I think that should originate from before 2.1.x. 🤔 

Anyway, I have triggered a new build with the right configuration and that is on MyGet now. @VitalyKnyazev would you be able to try the latest version here: https://www.myget.org/F/filepicker-plugin/api/v3/index.json ?

**Comment by vividos** [comment]
I checked out the 2.1.31 build on MyGet by opening the Android 9.0 assembly with ILspy and it now has the `[assembly: AssemblyConfiguration("release")]` attribute and no calls to Debug.Write() in OnActivityResult. @VitalyKnyazev please test this, I think it fixes the bug you're getting. Otherwise it's a different problem all along.

**Comment by vividos** [comment]
@VitalyKnyazev could you please update to 2.1.32-beta and verify that the error doesn't appear in the App enter fatals anymore? Thanks!

**Comment by DeerSteak** [comment]
Pre-release fixed this issue for me on an ancient Moto Droid Turbo. Thanks all!

**Comment by vividos** [comment]
Closing this issue, as it seems to be fixed.
