### ISSUE TITLE
Issue With Android and NavigationPage

### ISSUE THREAD

**Issue by dominion66** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#171]
## Expected Behavior
After Selecting file return to ContentPage

## Actual Behavior
After Selecting File returns to Root Page

## Steps to Reproduce the Problem

  1.Load Application with Navigation Page
  2.PushAsync to New Page with FilePicker
  3.Use button to pick file.  Select file or cancel to return.

## Specifications

  - NuGet package version: 2.1.34
  - Platform(s): Android API 28.  Works as Expected on IOS

**Comment by Kernste** [comment]
I have noticed this issue too on Android.

I have a button in a content page (not the root one). When a file is picked, I try to load a page depending on the name of the file the user picked.

The fact is this page can't be loaded because when the file picker is launched, the content page disappear and we get back to the root page (that doesn't know what to do with the filename returned).

As dominion66 said it was working on IOS, I believe there is an issue on Android.

**Comment by dominion66** [comment]
The issue I found that I was running into, is that for Android, when the app is minimized (FilePicker Minimizes the app when picking the file) and then resumed The OnAppearing Function of the root page is called, then the OnAppearing of the Content page is called.  The issue I had that the OnAppearing call on my root page interrupted the program from continuing to the content page, thus the Navigation stack appears to pop.  IOS doesn't call the OnAppearing function of the root page when appearing as why that continued to work.  I fixed my OnAppreaing code and FilePicker works as expected.

**Comment by vividos** [comment]
Good to hear you found the problem. Internally the file picker starts a new Activity from the currently visible one (which happens to be the Forms hosting activity) that is then hidden. The new activity is only used to start the file picker and receive its results.
