### ISSUE TITLE
FileNotFoundException: Could not find file "storage/emulated/0/Download/..."

### ISSUE THREAD

**Issue by javierescobare** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#18]
It only happens with the Download folder.

Same issue in the older repo: 
https://github.com/Studyxnet/FilePicker-Plugin-for-Xamarin-and-Windows/issues/34

Compiling against 8.0
Version 1.4.34-beta
Physical device: LG G4 Android 6.0

**Comment by jfversluis** [comment]
> It only happens with the Download folder.

You mean this only happens with files chosen from the Downloads folder?

**Comment by javierescobare** [comment]
Yes.

**Comment by jfversluis** [comment]
Could you by any chance provide a very simple repro repo? 🙂

**Comment by vividos** [comment]
I just made PR #49 that handles picking files from the Download folder on Android. It may be that this also fixes your problem.

**Comment by jfversluis** [comment]
New beta package available here: https://www.nuget.org/packages/Xamarin.Plugin.FilePicker/2.0.58-beta

Please let me know if this fixes your problem @javieresc97

**Comment by frooti7** [comment]
@jfversluis  it is not fixed in 2.0.58 betA

**Comment by frooti7** [comment]
@jfversluis  Is it fixed in the latest one?

**Comment by vividos** [comment]
@frooti7 You can also debug the problem for yourself, if you like. Just clone or download this repository, build the Plugin.FilePicker.sln solution (you can unload the iOS and UWP project, if you like), temporarily remove the NuGet project and reference the Plugin.FilePicker.Android project. After that you should be able to debug into the library and check out what is going on.

**Comment by bmgsmith** [comment]
Hello. Curious if this is working for you now? 
I am running V2.0.81-beta and I can pick files from the Android download folder no problem, however it fails when I pick files from the Android documents folder. The path returned is "content://com.android.externalstorage.documents/document/home%3AMyfileNameHere". Which, obviously, is not actually a path, it looks like a URL? Also, the "home" part of the path is odd, since that is not actually part of the path. The documents path should be something like "/storage/emulated/0/Documents"
Thoughts?

**Comment by vividos** [comment]
@bmgsmith there is a code path in the Android implementation which results in using ContentResolver to read the content:// URL by using a Stream object. the content:// URLs is the new Android way to pass files to other processes with also protecting the processes integrity.

It would be best if you just clone this repository, compile it with VS 2017 (it's really easy, see 
https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows/issues/18#issuecomment-400447095) and reference the assembly in your project (or even better, just add the .csproj files to your project). Then you can see where the problem is.

**Comment by bmgsmith** [comment]
I will give it a try in the next few days and let you know. Thanks.

**Comment by bmgsmith** [comment]
Had some success.
When I select a file from my Android Documents folder I get into the IOUtil class.getPath method, which returns null instead of a file path. When debugging I get into the below code block, which is the same block I get into when selecting from the Downloads folder. The difference is that the URI that the Downloads folder is: com.android.externalstorage.documents/document/primary%3ADownload%2FMyFile.txt while the URI from the Downloads folder is 
com.android.externalstorage.documents/document/home%3AMyFile.txt

So, the downloads URI contains the "primary" string and the "Download" string while the Documents contains only the "home" string. 

```
if (isExternalStorageDocument (uri)) {
	var docId = DocumentsContract.GetDocumentId (uri);
	string [] split = docId.Split (':');
	var type = split [0];

	if ("primary".Equals (type, StringComparison.OrdinalIgnoreCase)) {
		return Android.OS.Environment.ExternalStorageDirectory + "/" + split [1];
	}
	// TODO handle non-primary volumes
	
	!!!! I get here and leave code block without any action.
}
```

If I modify the method with the below else block then I get the correct result. 
However, I don't really know if this is a good general solution of if this is only fixing a very specific case that I am seeing. I will do some more testing.

```
if (isExternalStorageDocument (uri)) {
	var docId = DocumentsContract.GetDocumentId (uri);
	string [] split = docId.Split (':');
	var type = split [0];

	if ("primary".Equals (type, StringComparison.OrdinalIgnoreCase)) {
		return Android.OS.Environment.ExternalStorageDirectory + "/" + split [1];
	}
	else if ("home".Equals(type, StringComparison.OrdinalIgnoreCase))
	{
		return Android.OS.Environment.ExternalStorageDirectory + "/Documents/" + split[1];
	}

	// TODO handle non-primary volumes
}
```

**Comment by vividos** [comment]
@bmgsmith Thanks for your explanation. I added a passage to the plugin's README that on Android you don't always get a real file path in FilePath. The most reliable way to access the file is FileData.GetStream(). On Android this uses the ContentResolver class to resolve any picked file. Please try the latest NuGet beta package (2.0.114), there were some more related Android fixes. Thanks!
