### ISSUE TITLE
How to get file size of picked File?

### ISSUE THREAD

**Issue by manonaga2188** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#30]

**Comment by jfversluis** [comment]
Since IO is pretty platform specific, I guess you would have to implement something through the DependencyService. You feed it with the filename or path and then get the file size simply through something like: 

    FileInfo f = new FileInfo(fileName);
    long s1 = f.Length;

I don't feel this is something that should be part of the file picker plugin, since its purpose is to pick a file, not provide all kinds of information on the picked file.

**Comment by Aculeo** [comment]
I don't agree that this shouldn't be part of a file picker though, it's quite important to be able to determine file size without first having to load the file content. I want to limit the file size to 5MB for file selection, but I can't figure out a reliable way to get the size without having to load the DataArray.

Your solution with `FileInfo` doesn't work for Android `content://` URIs for example. A cross-platform solution for determining size without loading it would be awesome.

**Comment by vividos** [comment]
Unfortunately your content provider, say OneDrive, or a custom provider, may not tell you the length, but give you a non-seekable input stream that downloads content from the internet. How would you implement determining length then?

**Comment by Aculeo** [comment]
I understand. I guess my best option here might be reading the stream in chunks and stop if it exceeds my file limit.

**Comment by vividos** [comment]
That's the best solution for portability. You might get away, e.g. on UWP, to use an optimized path, since there you may always get a physical from the picker.
