### ISSUE TITLE
[Android] App terminates when picking large file

### ISSUE THREAD

**Issue by JayMansel** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#38]
Hello!

So when picking a large .mp4 file from the plugin, my app terminates, without any 'visible' exception (i.e. a try/catch around CrossFilePicker.Current.PickFile() does nothing).

So I downloaded the source code and found that it throws an exception in:

`                f.ReadFully (data);`
Line 151 in IOUtil.cs
> Handle must be valid.
> Parameter name: array

Android output says:

> Throwing OutOfMemoryError "Failed to allocate a 192503547 byte allocation with 16773232 free bytes and 149MB until OOM"

Now the plugin seems to handle this exception, however in the finally block when it tries to close the RandomAccessFile, 

`f.Close ();`
Line 157 in IOUtil.cs

It completely crashes out (nothing is caught), and debug output says a similar out of memory message:

> JNI DETECTED ERROR IN APPLICATION: JNI GetMethodID called with pending exception java.lang.OutOfMemoryError: Failed to allocate a 192503547 byte allocation with 16765216 free bytes and 149MB until OOM

Xamarin Forms v2.5.0.91635
FilePicker v2.0.8-beta

And the file I'm selecting is 184 MB.

Have tested on both an Android phone (low spec) and a Galaxy tablet (average spec), same issue.

Any ideas?

Cheers,
Jamie

**Comment by CarLoOSX** [comment]
Hey !! I would enable multidex in android app . Try this

**Comment by JayMansel** [comment]
Hello! Sorry been busy over the weekend.

Unfortunately Multi-Dex is already enabled :(

I was thinking of maybe parameterising the maximum file size allowed by the picker? I could have a stab at in and create a PR unless you are already working on such feature?

Cheers,
Jamie

**Comment by jfversluis** [comment]
Hi @JayMansel thank you for reporting this.
The `ReadFully` method was just implemented, so we weren't aware of this and aren't working on this yet. If you could provide for a PR that would be awesome!

**Comment by JayMansel** [comment]
Ok so I've _started_ to implement the file size checking. See [here](https://github.com/JayMansel/FilePicker-Plugin-for-Xamarin-and-Windows)

This get's around the little Android issue, however the data is still returned from the file picker; something of which I want to stop (pointless doing so if we've said it's too big). So I'll keep plugging away and hopefully have PR ready this week.

**Comment by jfversluis** [comment]
Great work! I'll be looking forward to it :)

**Comment by vividos** [comment]
I think the problem is here that the Android implementation tries to read the full file and store it in a byte array. For large files this won't work, since there's not enough memory available. The solution would be to give the PickFile() etc. calls an options object where one can specify if the filename should be returned, or the full file as byte array, or a System.IO.Stream where one can read from. Or any combination of it. The file picker doesn't support this at the moment.

**Comment by JayMansel** [comment]
I like the idea of returning a stream. I'm not sure if you'd be able to work with the file path however (please correct me if I'm wrong) as outside the context of Android's (and I believe iOS) file picker, your app wouldn't have access to that path (again correct me if I'm wrong), so you may get an access denied error.

I'll be having a stab tomorrow at not returning the byte array (return an empty one) if it exceeds the specified max size, and/or maybe return a stream, will have a look.

**Comment by jfversluis** [comment]
Returning a stream would be great. Would solve a lot of problems I think. Not sure on the implications for permissions and such.

I think iOS will be OK, since it copies the file to the local apps sandbox and works from there. on Android you might need special permissions. But on the other hand, is it so different from what we're doing now?

**Comment by JayMansel** [comment]
Okay so I have PR, here #52 

This returns an empty byte array if the file exceed the specified maximum file size.

Have a peruse through, see what you think.

**Comment by Weldryn** [comment]
As @vividos suggested, returning a `System.IO.Stream` instead of a file path and a `byte[]` would definitely be a way better feature. It would allow much more flexibility for the dev than a `byte[]` because of the available stream API and are [widely](https://docs.microsoft.com/en-us/dotnet/api/system.io.stream?view=netframework-4.5#applies-to) supported across platforms. Streams also consumes a lot less memory in comparison which would resolve memory overflow issues amongst other things that are a 'no go' for cases where big amount of data is involved like data uploading, etc

Furthermore it would make the `FileData` completely platform agnostic by getting rid of the array and the path.

Regarding permissions, on Android and iOS at least, I believe the requirements are already met through `WRITE_EXTERNAL_STORAGE ` /`READ_EXTERNAL_STORAGE ` and iCloud Driver configuration.

Of course, this would a breaking change but I do really think it worth it. Maybe I should start a new discussion about this?...

**Comment by frooti7** [comment]
@jfversluis  is this fixed yet?

**Comment by jfversluis** [comment]
Not yet

**Comment by frooti7** [comment]
My app doesnt crash but it is really slow and a black screen appears....
Any suggestion for a solution? @jfversluis

**Comment by frooti7** [comment]
@jfversluis  any updates about the slow thing?

**Comment by jcus0006** [comment]
Any update on this? The version am using simply returns an empty FileData object which gives the same impression as if the user cancelled. What seems to be the maximum accepted size? If anything I can specify this on the same screen as the Browse button.

**Comment by jfversluis** [comment]
Nothing yet, an (unfortunately) don't expect anything soon. Will be away for the coming month and I think there are more pressing issues than this one on the issue list. I'd be happy to look at any PRs though.

**Comment by jcus0006** [comment]
Ok! any idea about the Max accepted size, please?

**Comment by ganggoo** [comment]
Hoi Guys, for me it is a big problem at the moment , the FilePicker doesen't work at all

**Comment by jfversluis** [comment]
I'm sorry to hear that. Unfortunately, I am caught up in a lot of other stuff right now and can't really look into this.

**Comment by vividos** [comment]
From working with the FilePicker library code more, I found that there's a solution that is already implemented! Don't bother accessing the property DataBytes, as it would call ReadFully() and try to read the whole file into memory. Instead just call fileData.GetStream() and read the stream.

We also just released the NuGet package version 2.0.106-beta which has some bug fixes related to Android.

**Comment by vividos** [comment]
Actually I was wrong. The Android implementation reads the file into a byte[], then it's not used. That slowed down opening large files. I fixed this in the latest commit abe5b538542582990427c35133d307258ab3ed47 and shoud be in 2.0.109-beta.

**Comment by vividos** [comment]
Did anyone have a chance to test out the approach using the latest 2.0.114-beta and using GetStream() instead of accessing DataBytes? I think that fixes all the problems with large files.

**Comment by vividos** [comment]
I believe this issue is fixed as described above. Closing this issue.
