### ISSUE TITLE
Please release stable version

### ISSUE THREAD

**Issue by shrutigoyal123** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#57]
@jfversluis 

  1.If I work with version 2.0.58 version then getting issue that picking file from google drive it is not giving google drive path.and data array is also 0.
 2.after using 2.0.63 version this issue has been resolved
 3.but with beta version I can't deliver my live project. It's a request to release stable version.

**Comment by jfversluis** [comment]
Hi @shrutigoyal123 thank you for using the package!

If I understand you correctly it works for you in the 2.0.63 package but you are unable to use it since it is labeled beta? Although, this is of course a choice that only you can make. The only thing I would do is take of the beta label and it would be the exact same code. So, the only thing holding you back right now is this arbitrary label.

I plan to release a stable version soon, but not sure when exactly. On the other hand; if this package works for you and seems stable, why not use it?

**Comment by shrutigoyal123** [comment]
Thanks for soonest reply.

Yes, I'm using this version. It saved my day.
