### ISSUE TITLE
iOS problem

### ISSUE THREAD

**Issue by kpetryla** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#58]
## Expected Behavior
opening file picker dialog

## Actual Behavior
Nothing happens on UI and I'm getting Warning in output.

Warning: Attempt to present <UIDocumentMenuViewController: 0x111e0df60> on <Xamarin_Forms_Platform_iOS_PlatformRenderer: 0x10bc79e30> whose view is not in the window hierarchy!

filepicker version 2.0.64

**Comment by jfversluis** [comment]
Thank you for reporting!

Would it be remotely possible to create a reproduction project for this?

**Comment by kpetryla** [comment]
I've noticed that it works on first page of my app but when I navigate to other for example path looks like "LoginPage/Navigation/MainPage/PageA" it does't work. I'll let you know as soon as it will be possible for me to create a reproduction project for this.

Thank you for fast reply.

**Comment by jfversluis** [comment]
That would be great, thank you!

**Comment by TobiasB2** [comment]
I can confirm this bug. 
The reason is that in the methods TakeMediaAsync and DidPickDocumentPicker the picker view is presented via the root view. If the root view has children the visible child has to present the view.

The solution is shown in issue #21. You have to iterate though the children from the root view until you reach the last child, and then present the view via that child.
That worked for me.

**Comment by vividos** [comment]
This is fixed in the latest NuGet package 2.0.106-beta. Please upgrade and test. Thank you!
