### ISSUE TITLE
Which plugin is the active one?

### ISSUE THREAD

**Issue by scastria** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#63]
There seems to be about 4 of these plugins that are all forked from each other.  This makes it very difficult to know which one to use that will have support in the future.  @jfversluis seems to be a contributor on most of them.  I have two questions:

1. Anyway to remove the old ones so that it is clear which nuget to choose?
2. Can you add WPF support now that Xamarin.Forms has added support for it?

**Comment by jfversluis** [comment]
Hi! Thank you for finding this.

1. No, unfortunately not. Because they have forked the project I am listed as a contributor on most of them automatically. But I do not have the rights to publish (or take down) those NuGet packages. Including, the one from the original project. The author there does not respond to anything anymore. That is why I decided to create one more fork and try to incorporate all the changes from the other forks. I think this project is the most complete one right now.

2. That would be a great addition. I don't think I will have time for that in the near future, but I would gladly take a PR that makes this happen. Opened #64 for that.
