### ISSUE TITLE
OpenFile on Android doesn't work: file not found

### ISSUE THREAD

**Issue by TomONeill** [jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows#71]
## Description
When calling `CrossFilePicker.Current.OpenFile("/storage/emulated/0/Music/Over_the_horizon.mp3");`, which is a default song on a Samsung device, intent chooser shows, but after selecting Play Music, the file does not play. A toast is shown stating the song cannot be played. This behaviour is the same with PDF files (though then with Google Drive's PDF viewer).

## Specifications

  - NuGet package version: 2.0.64-beta
  - Platform(s): Android

## Logcat
`07-18 12:09:23.264  2717  3202 V MediaPlayerService: Create new media retriever from pid 5060`
`07-18 12:09:23.264  2717  5255 V GenericSource: onPrepareAsync`
`07-18 12:09:23.264  2717  5255 E FileSource: Failed to open file '/mounted/file:/storage/emulated/0/Music/Over_the_horizon.mp3'. (No such file or directory)`
`07-18 12:09:23.264  2717  5255 E GenericSource: Failed to create data source!`
`07-18 12:09:23.264  2717  5254 V NuPlayer: performDecoderFlush audio=2, video=2`
`07-18 12:09:23.264  2717  5254 I GenericSource: mExtractor NULL and mUri exists`
`07-18 12:09:23.264  2717  5254 V NuPlayer: enableInbandTextFromExtr`
`07-18 12:09:23.264  2717  5254 I GenericSource: mExtractor NULL and mUri exists`
`07-18 12:09:23.264  2717  5254 D NuPlayerDriver: notifyListener_l(0xaf210180), (100, 1, -2147483648), loop setting(0, 0)`
`07-18 12:09:23.264  2717  5254 V MediaPlayerService: [12] notify (0xb0cbb780, 100, 1, -2147483648)`
`07-18 12:09:23.264  5060  5192 V MediaPlayer: message received msg=300, ext1=0, ext2=0`
`07-18 12:09:23.264  5060  5192 V MediaPlayer: Received SEC_MM_PLAYER_CONTEXT_AWARE`
`07-18 12:09:23.264  5060  5192 V MediaPlayer: callback application`
`07-18 12:09:23.265  5060  5192 V MediaPlayer: back from callback`
`07-18 12:09:23.265  5060  5192 V MediaPlayer: message received msg=100, ext1=1, ext2=-2147483648`
`07-18 12:09:23.265  5060  5192 E MediaPlayer: error (1, -2147483648)`
`07-18 12:09:23.265  5060  5192 V MediaPlayer: callback application`
`07-18 12:09:23.265  5060  5192 V MediaPlayer: back from callback`
`07-18 12:09:23.265  5060  5256 E MediaMetadataRetriever: setDataSource - FileNotFoundException`
`07-18 12:09:23.265  5060  5256 D AudioPreviewActivity: Failed to set data source using MediaMetadataRetriever: file:///mounted/file%3A/storage/emulated/0/Music/Over_the_horizon.mp3 with exception: java.lang.IllegalArgumentException`

**Comment by TomONeill** [comment]
Removing `Android.OS.Environment.ExternalStorageState, ` from [this line](https://github.com/jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows/blob/develop/src/Plugin.FilePicker/Plugin.FilePicker.Android/FilePickerImplementation.cs#L137) fixes the problem. Any particular reason that's there?

**Comment by AmrAlSayed0** [comment]
According to this [Android.OS.Environment.ExternalStorageState](https://developer.xamarin.com/api/property/Android.OS.Environment.ExternalStorageState/) and this [Enviroment.getExternalStorageState()](https://developer.android.com/reference/android/os/Environment#getExternalStorageState()
) return a string of the state of the external storage, one of
MEDIA_UNKNOWN
MEDIA_REMOVED
MEDIA_UNMOUNTED
MEDIA_CHECKING
MEDIA_NOFS
MEDIA_MOUNTED
MEDIA_MOUNTED_READ_ONLY
MEDIA_SHARED
MEDIA_BAD_REMOVAL
MEDIA_UNMOUNTABLE
I don't know why is that used as directory for the file. Doesn't make sense. May be he meant Android.OS.Environment.ExternalStorageDirectory, but even then it will not work if you pass an absolute URI instead of just the file name.

**Comment by vividos** [comment]
Certainly the one who coded  this meant ExternalStorageDirectory instead of ExternalStorageState. I don't know the purpose for the OpenFile() and SaveFile() methods, but I guess they were created so that picked files can be moved into the external storage directory and can be opened from there. The Android, iOS and UWP implementations are all very similar and use only relative file paths. I guess they were never meant to be passed full paths to them.

**Comment by vividos** [comment]
I replaced ExternalStorageState with ExternalStorageDirectory, just to fix the obvious error; available in the next AppVeyor build or on the develop branch.

**Comment by TomONeill** [comment]
Yah, that makes sense. Don't know why I didn't see that for myself. Thank you for the fix!
